[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv

upload_speed = 921600
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  mikalhart/TinyGPSPlus@^1.0.3
  WiFi
  HTTPClient

build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -I include
  -I lib/kissfft
  -I lib/tflite-micro-minimal
  -I lib/tflite-micro-minimal/tensorflow
  -I lib/tflite-micro-minimal/tensorflow/lite
  -I lib/tflite-micro-minimal/tensorflow/lite/micro
  -DCORE_DEBUG_LEVEL=3
  -DTF_LITE_STRIP_ERROR_STRINGS
  -DTF_LITE_DISABLE_X86_NEON
  -include tensorflow/lite/kernels/internal/ruy_profiler_stub.h
  -fno-exceptions
