[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

; ----- FLASH: chuẩn DevKitC-1 (8MB) -----
board_build.flash_size = 8MB
board_build.partitions = default.csv
board_build.flash_mode = qio
board_build.flash_freq = 80m
build_src_filter = +<*> -<model/> -<crynet_tiny_no_psram.cc>

; ----- PSRAM -----
board_build.arduino_psram = enabled

lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  mikalhart/TinyGPSPlus@^1.0.3
  WiFi
  HTTPClient

build_unflags =
  -std=gnu++11

build_flags =
  -std=gnu++17
  -I include
  -I lib/kissfft
  -I lib/tflite-micro-minimal
  -I lib/tflite-micro-minimal/tensorflow
  -I lib/tflite-micro-minimal/tensorflow/lite
  -I lib/tflite-micro-minimal/tensorflow/lite/micro
  -I lib/tflite-micro-minimal/third_party/ruy
  -DCORE_DEBUG_LEVEL=0
  -DTF_LITE_STRIP_ERROR_STRINGS
  -DTF_LITE_DISABLE_X86_NEON
  -include tensorflow/lite/kernels/internal/ruy_profiler_stub.h
  -fno-exceptions
  -Os
  -ffast-math
  -Wno-error=unused-variable
  -Wno-error=unused-function
